sudo: false
matrix:
  include:
    - language: php
      php:
        - 7
      script:
        - '.travis-build/phplint .'
    - language: node.js
      node_js: '10.20.1'

before_install:
  - npm i -g npm@v6.14.8
install:
  - npm install
after_success:
  - npm run build
  - rm -rf node_modules
  - tar -czf conference.tar.gz *
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "Njx2CGRmecEUUUw9JpW07x7q4PLyKkHLTOr1XT4j26OT62RlKuHYkcPYQW5IaFNLlj9bXya/RcUhVFFVgneXfqMXshTdvUqs0r1pEGaNNeMx13XqaJlV4Iq6TGRmH4Q0tWsEWWYZzGAlSXPh88RyepTgGWB5WHKTNFvASG+nCs0PiexB5K2F3EXsx/BTqT9E1FSsA4ygLzf2g1HytP0UIzzML07tGIunVVoBWXL3nd7GWs0gcALklKzGv6t/UlJytVdHYhsA19Yj+xUAeKAoKWn+1ggdsRcg7fI/arpt7WJdFkoZV44zor6ymmMSbnlfFE1FPKaLqTOUg417fGZFs12g7DHHu8Gy/rYH63HH1ftaGHQKk2okKVNqgZYRq2bKYU2V3/9FupoqmIOGslNRdV3aapiUH/h3D5S/FtHqe9NcBkDIvVqBdR2AzU248owUQOvHPZXhDTB70k0taWwPP7omKx2qQJjlPSZCEj2MJGGyCiJO0DaNYvijw/2Nbhj8kkSrPBoZ37KYSDAr9uOpJozO756+RmW5igSwhnaiENOSrybxG5zATxK54xsJ5f0qcNr976QhTikcnWBTkPbGw/DvB6gN+kYprFv7b2Ot4rnW8R4pv/CBEyp+B5WHkFn9q/qEH/k0HQZfqKR41P7lRdmK02SYoLCgIwhqz0Xo+jk="

  file: conference.tar.gz
  overwrite: true
  on:
    repo: AppStateESS/conference
    branch: master
    tags: true
