sudo: false
matrix:
  include:
    - language: php
      php:
        - 7
      script:
        - '.travis-build/phplint .'
    - language: node.js
      node_js: '10.20.1'

before_install:
  - npm i -g npm@v6.14.8
install:
  - npm install
after_success:
  - npm run build
  - rm -rf node_modules
  - tar -czf conference.tar.gz *
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "ariUj2MD+CxG5dBikQMoKMRh2SjcX1j7p0/xMr2vb9hJTRIr2/au3z0X68msaa96fbIxRsr7bwXxGQMaK2tpzbtiunxcVLrVNX46qCSgF+nnNtqpBviFxVj8DclGcl6ekfK5s+3wX+RcjS90GW7BKoXn1BZ5pPrhPRG5JlSI5/fut/DWFkFJ6z0Vbq3Jr42AW7ESH3HWP2nDxDv8KFeGu5CJiRr31KxMe7xCQ9r3S+ck3Bjxg4CU8e7XgTp91tN4rtHrgevbGK0tGfG2zL4qc3q4Xd6lfBpcKYvfpdflz0Y8/Ix1tu8BMMaMec/9fgCiTzL53YNqFD4OdRknwWlLH9U7aWgtFGyXL1hKVFWNvXdCH/ybxpj8gL84Pjj4rY1CXDcEcs2oZCzCGGRrSSNltAJ2/7z9FavRXiuHqcIHt0Mil8VdE2zqQIFcSMyQgq5SwqEavP8+MS38ahHhO/floNAqV38H+d2HRTASmkNCuw2P6RbmVYaujpJ0EpV7G+vdjDBhxLimVuABTQJLZpsBda2ogmafdy6C7iyh2mPBcm6lkKB/iJve8bscoelEpz8iM9oDY+ka4iOcAdHlek4DX8qkUeNcjhLGvki7dONUbUk8yFOGSPbyZz6CN0o8eyQpr/GsawE3j98ugOVYxS1oVHeP61DjQFQDXf/bMx0aMPU="
  file: conference.tar.gz
  overwrite: true
  on:
    repo: AppStateESS/conference
    branch: master
    tags: true
