sudo: false
matrix:
    include:
        - language: php
          php:
            - 7
          script:
            - '.travis-build/phplint .'
        - language: node.js
          node_js: "10.20.1"

before_install:
  - npm i -g npm@v6.14.8
install:
  - npm install
after_success:
  - npm run build
  - rm -rf node_modules
  - tar -czf conference.tar.gz *
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: lf0dZxq3ICWnK4ZercgqcAESuAdUqjQDu8xCNKS7qTbe/mH1Rb/1hXn9825Yh/agoAXivIi+fNfeTva9gRRsvCK+2tOuwMNIS+jL8X0IbKi9KgNQSmQ54gfcw1C+L4J7TnR6WVG4Pspyhze4yAKbdyo7S3NCsqFdh/geWq7kZdH7jU6pjfn63hnVORZehRAU+ScbWs2AFzXdacbMKubpSHqiQCtdtB7DaTPcPTLsNQo4PIumwEqyeyXlW4OcI6ZLBBpFoWOJ8WEw0tPi/mP0JNH/RDBqeLFJQ+OD07Vquz4pyId6H4lxUZI6FahJ+NFf9FHoJto0rxGpnhVaILrtFCSYN961zoQIHh218GGofD68x2c9VdoKOxGinFeFCsPBLkuxsYc9VvSq9ivPrfzrZc2J7vko+/Q3ox5Ib0nntbDKgxlIqB9Lry6kRiTDGCSoPRzaq/fCqFmiK/HlspyH7Zcglzh5geVH5lKbjpHd+QnlRItSRDnTjktwnEh3aeGuFwjup7j6armr0vngvFjoAiKDdM2XbanaS3DzsS0yLhzihExiexEHE8mJdMPvV6xiB2lrPVbkWpyHHBtQh9otzxzsZEuuT6ygsN2fXQSOYl5BLf7W+Ne99BZx4M2+wNW+bDoj/UB7XjmkuS48mrIrUju3kfvgav0IMO8vRVJQQOo=
  file: conference.tar.gz
  overwrite: true
  on:
    repo: AppStateESS/conference
    branch: master
    tags: true
